# Use the latest AlmaLinux image
FROM almalinux:latest

# Install Git and Node.js
RUN dnf -y update && \
    dnf -y install git nodejs

COPY . /RepuChain
# Clone the repository
#RUN git clone https://github.com/jenniferduan45/RepuChain.git

# Install Truffle globally
RUN npm install -g truffle

# Set working directory to backend folder
WORKDIR /RepuChain/frontend

# Install project dependencies
RUN npm install

# Expose port 3001
EXPOSE 3001

# Start the application
CMD ["npm", "start"]

