# Use the latest AlmaLinux image
FROM almalinux:latest

# Declare build-time variable
ARG REACT_APP_API_URL

# Install Git and Node.js
RUN dnf -y update && \
    dnf -y install git nodejs make gcc-c++

COPY . /RepuChain
# Clone the repository
#RUN git clone https://github.com/jenniferduan45/RepuChain.git

# Install Truffle globally
RUN npm install -g truffle

# Set working directory to backend folder
WORKDIR /RepuChain/frontend

# Set environment variable for build time
ENV REACT_APP_API_URL=$REACT_APP_API_URL

# Install project dependencies
RUN npm install

# Expose port 3000
EXPOSE 3000

# Start the application
CMD ["npm", "start"]

