# Use the official Node.js LTS version
FROM node:16

# Set working directory
WORKDIR /app

# Install Truffle globally
RUN npm install -g truffle

# Copy package.json and package-lock.json
COPY backend/package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the backend code
COPY backend/ .

# Expose port 3001
EXPOSE 3001

# Start the application
CMD ["npm", "start"]